#include "compute-bam-region-features.h"

#include <xoos/io/htslib-util/htslib-ptr.h>
#include <xoos/io/htslib-util/htslib-util.h>

#include "compute-bam-features/alignment-reader.h"
#include "compute-bam-features/read-processing.h"
#include "core/config.h"
#include "core/variant-info-serializer.h"
#include "util/log-util.h"

namespace xoos::svc {

ComputeBamRegionFeatures::ComputeBamRegionFeatures(const vec<AlignmentReader>& alignment_readers,
                                                   ComputeBamFeaturesParams params,
                                                   LockedTsvWriter* writer)
    : _alignment_readers(alignment_readers), _params(std::move(params)), _writer(writer) {
}

void ComputeBamRegionFeatures::ResetForRegion() {
  _read_names.clear();
  _current_read_id = 0;
  _bam_features.Clear();
  _vcf_features.clear();
  _vcf_positions.clear();
}

BamRegionFeatureCollection ComputeBamRegionFeatures::ComputeBamFeatures(
    const Region& region,
    const std::string& ref_sequence,
    const std::optional<VarIdToVcfFeatures>& vcf_features,
    const std::optional<StrUnorderedSet>& skip_variants) {
  // This function is designed to be used for feature extraction for a given genomic region. It can be run in parallel
  // or in sequence to compute features for different genomic regions with a region being as large as a full chromosome.
  // This function is also designed to take in multiple BAM files, with each BAM file's alignments to the given region
  // checked to identify all alignments that overlap the region over all input BAM files.
  ResetForRegion();

  // Check if there are VCF Features provided. If VCF features are passed we want to limit the feature computation
  // only to positions where there are observed variants, as only features at these positions will be used in
  // subsequent training and filtering applications.
  if (vcf_features.has_value()) {
    _vcf_features = vcf_features.value();
    if (_vcf_features.empty()) {
      // VCF Features were specified, but no features for this chromosome. No need to parse region
      return _bam_features;
    }
    // Have VCF Features for the chromosome, check if they intersect the region at all
    // Pad by one to ensure that edge cases are covered
    for (const auto& [vid, feat] : _vcf_features) {
      if (region.start <= vid.pos - 1 && region.end >= vid.pos + 1) {
        _vcf_positions.insert(vid.pos);
      }
    }
    if (_vcf_positions.empty()) {
      // VCF Features were specified, but no features for this region. No need to parse region
      return _bam_features;
    }
  }

  // loop through all BAM files and extract features from the alignments overlapping the target region. BAM files are
  // processed individually but feature values are cumulatively incremented with alignments across all BAM files.
  for (const auto& alignment_reader : _alignment_readers) {
    ComputeFeaturesForBam(region, ref_sequence, skip_variants, alignment_reader);
  }
  ProcessVariantFeatures();
  return _bam_features;
}

void ComputeBamRegionFeatures::ComputeFeaturesForBam(const Region& region,
                                                     const std::string& ref_sequence,
                                                     const std::optional<StrUnorderedSet>& skip_variants,
                                                     const AlignmentReader& alignment_reader) {
  // Add one to the end position to make it end inclusive. This is so that we correctly include reads that start
  // at the end position computing depth for insertion at the end
  const auto tid = io::SamHdrName2Tid(alignment_reader.hdr.get(), region.chrom);
  const auto alignments = io::SamItrQueryI(alignment_reader.idx.get(), tid, region.Start(), region.EndInclusive());
  if (alignments == nullptr) {
    throw error::Error("Failed to query region {}:{}-{}", region.chrom, region.start, region.end);
  }

  // Iterate through the specified region of bam file
  io::Bam1Ptr b(bam_init1());
  if (b == nullptr) {
    throw error::Error("Failed to allocate memory for bam record");
  }
  while (true) {
    const bool has_next = io::SamItrNext(alignment_reader.fp.get(), alignments.get(), b.get());
    if (!has_next) {
      break;
    }
    // skip alignments that are either unmapped, duplicated, secondary, or supplementary
    static constexpr auto kBitMask = BAM_FUNMAP | BAM_FDUP | BAM_FSECONDARY | BAM_FSUPPLEMENTARY;
    if ((b->core.flag & kBitMask) != 0) {
      continue;
    }
    // skip alignments that have low mapping quality or don't have valid contig IDs or alignment positions
    if (b->core.qual < _params.min_mapq || b->core.tid < 0 || b->core.pos < 0) {
      continue;
    }
    // Sanity check to skip any alignments that start and end outside the region of interest.
    if (std::cmp_greater(b->core.pos, region.end)) {
      continue;
    }

    const std::string read_name = bam_get_qname(b.get());
    // exclude artificial haplotypes generated by GATK
    if (read_name.starts_with("HC")) {
      continue;
    }

    ComputeFeaturesForRead(region, ref_sequence, skip_variants, b.get());
  }
}

void ComputeBamRegionFeatures::ComputeFeaturesForRead(const Region& region,
                                                      const std::string& ref_sequence,
                                                      const std::optional<StrUnorderedSet>& skip_variants,
                                                      const bam1_t* b) {
  if (_params.decode_yc == YcDecodeMethod::kSplit && IsDuplexProtocol(_params.sequencing_protocol)) {
    // If the sequencing protocol is duplex and the YC tag decoding method is "Split", then
    // split the duplex read into two simplex reads (R1, R2) using the YC tag.
    auto decoded_records = yc_decode::DecodeToBamRecords(b);
    if (std::holds_alternative<std::monostate>(decoded_records)) {
      // No decoded records indicates that the YC tag is either absent or empty.
      // If input data is a hybrid of duplex reads and simplex reads, then this is a simplex read.
      if (kSimplexReadFamilySize >= _params.min_family_size) {
        ComputeBamFeaturesHelper(b, ref_sequence, region, _read_names, _current_read_id, skip_variants);
      }
    } else if (std::holds_alternative<io::Bam1Ptr>(decoded_records)) {
      // one decoded record
      if (kSimplexReadFamilySize >= _params.min_family_size) {
        const auto r1 = std::move(std::get<io::Bam1Ptr>(decoded_records));
        ComputeBamFeaturesHelper(r1.get(), ref_sequence, region, _read_names, _current_read_id, skip_variants);
      }
    } else {
      // two decoded records
      if (kDuplexReadFamilySize >= _params.min_family_size) {
        const auto [r1, r2] = std::move(std::get<std::pair<io::Bam1Ptr, io::Bam1Ptr>>(decoded_records));
        ComputeBamFeaturesHelper(r1.get(), ref_sequence, region, _read_names, _current_read_id, skip_variants);
        ComputeBamFeaturesHelper(r2.get(), ref_sequence, region, _read_names, _current_read_id, skip_variants);
      }
    }
  } else {
    ComputeBamFeaturesHelper(b, ref_sequence, region, _read_names, _current_read_id, skip_variants);
  }
}

void ComputeBamRegionFeatures::ProcessVariantFeatures() {
  // We only want to compute certain somatic tumor normal related features if we are computing features in the somatic
  // tumor normal workflow and have a set tumor sample name.
  const bool tally_tumor_normal_features =
      (_params.tumor_sample_name.has_value() && !_params.tumor_sample_name->empty()) ||
      (_params.tumor_rg_ids.has_value() && !_params.tumor_rg_ids->empty());

  // Gather variants at their reference feature positions. Since ref feature positions are offset by 1 for deletions,
  // gathering variants at their positions (instead of ref feature position) would lead to an incorrect tally.
  std::map<u64, vec<VariantId>> ref_pos_to_vids{};
  for (const auto& [id, f] : _bam_features.var_features) {
    ref_pos_to_vids[id.GetRefFeaturePos()].emplace_back(id);
  }

  // Update derived feature values (e.g. mean, allele frequencies) for variant and reference features at each
  // reference position.
  for (auto& [pos, vids] : ref_pos_to_vids) {
    UpdateDerivedFeatureValues(_bam_features.var_features,
                               _bam_features.ref_features,
                               vids,
                               _params.duplex_lowbq == DuplexLowbqMode::kInclude);
    if (tally_tumor_normal_features) {
      UpdateTumorNormalFeatures(_bam_features, vids, _params.duplex_lowbq == DuplexLowbqMode::kInclude);
    }
  }

  // At this stage, the features for all alignments in the target region have been computed. Although all features for
  // the variant/reference alleles are computed at each alignment position, only the user-selected feature columns
  // would be converted to their string representations.
  if (_writer == nullptr) {
    return;
  }
  vec<vec<std::string>> region_feature_strings;
  region_feature_strings.reserve(_bam_features.var_features.size());
  for (const auto& [pos, vids] : ref_pos_to_vids) {
    // convert feature values to their string representations.
    for (const auto& vid : vids) {
      const auto& feature_strings = SerializeFeatureHelper(vid, _bam_features, _params.feature_cols);
      if (!feature_strings.empty()) {
        region_feature_strings.emplace_back(feature_strings);
      }
    }
  }
  _writer->AppendRows(region_feature_strings);
}

void ComputeBamRegionFeatures::PopulateRegionsQueue(const StrMap<RefRegion>& contig_map,
                                                    const StrMap<vec<Interval>>& bed_regions,
                                                    vec<Region>& regions_queue,
                                                    const u64 max_region_size_per_thread) {
  if (!bed_regions.empty()) {
    GetGenomicRegionsForBedFile(contig_map, bed_regions, regions_queue, max_region_size_per_thread);
  } else {
    GetGenomicRegionsForChromosome(contig_map, regions_queue, max_region_size_per_thread);
  }
}

void ComputeBamRegionFeatures::GetGenomicRegionsForBedFile(const StrMap<RefRegion>& contig_map,
                                                           const StrMap<vec<Interval>>& bed_regions,
                                                           vec<Region>& regions_queue,
                                                           const u64 max_region_size_per_thread) {
  // This function breaks up BED entries per contig into smaller regions of at most a set size that can be used for
  // parallel processing.
  std::optional<std::string> prev_chrom = std::nullopt;
  std::optional<Interval> prev_interval = std::nullopt;
  for (const auto& [chrom, intervals] : bed_regions) {
    // skip if the contig has no alignments
    if (!contig_map.contains(chrom)) {
      continue;
    }

    if (!prev_chrom.has_value() || prev_chrom.value() != chrom) {
      // this is the first interval in the chromosome; no previous interval
      prev_interval = std::nullopt;
    }
    prev_chrom = chrom;

    // Add intervals to the list of regions. If the interval is too big break up the interval into smaller chunks
    for (const auto& interval : intervals) {
      const u64 region_start = interval.start;
      const u64 region_end = interval.end;
      for (u64 start = region_start; start <= region_end + 1; start += max_region_size_per_thread) {
        const u64 end = std::min(start + max_region_size_per_thread, region_end + 1);
        regions_queue.emplace_back(chrom, start, end, prev_interval);
        prev_interval = Interval{start, end};
      }
    }
  }
}

void ComputeBamRegionFeatures::GetGenomicRegionsForChromosome(const StrMap<RefRegion>& contig_map,
                                                              vec<Region>& regions_queue,
                                                              const u64 max_region_size_per_thread) {
  // This function breaks up contigs into smaller regions up to a certain size, which are used to compute features in
  // parallel
  std::optional<std::string> prev_chrom = std::nullopt;
  std::optional<Interval> prev_interval = std::nullopt;
  for (const auto& [chrom, region] : contig_map) {
    // leftmost aligned position of the contig
    const u64 region_start = region.start_position;
    // rightmost aligned position of the contig
    const u64 region_end = region.end_position;

    if (!prev_chrom.has_value() || prev_chrom.value() != chrom) {
      // this is the first interval in the chromosome; no previous interval
      prev_interval = std::nullopt;
    }
    prev_chrom = chrom;

    // Add regions to the list up to the max region size. Individual threads will run BAM feature computation per each
    // of these regions.
    for (u64 start = region_start; start <= region_end + 1; start += max_region_size_per_thread) {
      const u64 end = std::min(start + max_region_size_per_thread, region_end + 1);
      regions_queue.emplace_back(chrom, start, end, prev_interval);
      prev_interval = Interval{start, end};
    }
  }
}

vec<std::string> ComputeBamRegionFeatures::SerializeFeatureHelper(const VariantId& vid,
                                                                  const BamRegionFeatureCollection& bam_features,
                                                                  const vec<FeatureColumn>& feature_cols) {
  // Helper function to convert selected feature values to strings. This function is used primarily for generating
  // strings to be output to file.

  const bool has_tumor = !bam_features.tumor_ref_features.empty() || !bam_features.tumor_var_features.empty();
  const bool has_normal = !bam_features.normal_ref_features.empty() || !bam_features.normal_var_features.empty();

  vec<std::string> feature_strings;
  if (has_tumor || has_normal) {
    const auto& feat_row = bam_features.GetTumorNormalBamFeatureTuple(vid);
    if (feat_row.has_value()) {
      feature_strings = VariantInfoSerializer::SerializeTumorNormalBamFeatureRow(
          feature_cols, vid, feat_row.value(), has_tumor, has_normal);
    }
  } else {
    const auto& feat_row = bam_features.GetBamFeatureTuple(vid);
    if (feat_row.has_value()) {
      feature_strings = VariantInfoSerializer::SerializeBamFeatureRow(feature_cols, vid, feat_row.value());
    }
  }

  return feature_strings;
}

void ComputeBamRegionFeatures::ComputeBamFeaturesHelper(const bam1_t* record,
                                                        const std::string& ref_seq,
                                                        const Region& region,
                                                        ReadNameToId& read_names,
                                                        ReadId& current_read_id,
                                                        const std::optional<StrUnorderedSet>& skip_variants) {
  // This function extracts features for an individual BAM record. It assumes that the record has already been checked
  // for mapping quality and flag stats. This function should only be used for records that have passed checks for
  // minimum mapping quality, flag stats, and are aligned within the region of interest. First extract alignment
  // positions for all CIGAR operators in the BAM record determine the alignment's end position on the reference

  if (record->core.pos < 0) {
    WarnAsErrorIfSet("Found alignment with start position < 0: '{}'", bam_get_qname(record));
    return;
  }

  const auto& align_ops = GetAlignOpInfos(record, ref_seq);
  if (align_ops.empty()) {
    // no alignment information; skip this record
    return;
  }

  const auto bam_pos = static_cast<u64>(record->core.pos);
  const auto reference_end = align_ops.back().ref_pos + align_ops.back().op_len;
  // Sanity check to make sure the read doesn't start and end before the region of interest
  if (reference_end < region.start || bam_pos >= region.end) {
    return;
  }
  if (!_vcf_positions.empty()) {
    // check whether the alignment intersects the VCF positions for this region. We only want to extract features from
    // reads that overlap an observed variant in the VCF positions set
    auto lower = _vcf_positions.lower_bound(bam_pos);
    auto upper = _vcf_positions.upper_bound(reference_end);
    if (lower == upper) {
      return;
    }
  }

  // check whether thresholds are set for max number of variants allowed per alignment
  const bool check_num_var = _params.max_read_variant_count > 0;
  const bool check_num_var_norm = _params.max_read_variant_count_normalized > 0;
  if (check_num_var || check_num_var_norm) {
    u32 num_var{0};
    if (skip_variants.has_value() && !skip_variants->empty()) {
      // count variants in the alignment, ignoring any known variants
      num_var = CountVariantsInRead(align_ops, record, ref_seq, region.chrom, skip_variants.value());
    } else {
      // naively count variants in the alignment
      num_var = CountVariantsInRead(align_ops);
    }
    if ((check_num_var && num_var > _params.max_read_variant_count) ||
        (check_num_var_norm && (static_cast<float>(num_var) / static_cast<float>(GetAlignmentLength(align_ops))) >
                                   _params.max_read_variant_count_normalized)) {
      // the alignment has too many variants; do not extract any features from it
      return;
    }
  }
  // extract a numeric ID from the read name
  const auto read_id = GetReadId(read_names, bam_get_qname(record), current_read_id);

  // extract features for variants and reference alleles using the extracted CIGAR operator alignment info. Computed
  // features are added to the maps that has been passed in.
  const AlignContext align_ctx(_params, align_ops, record, region, ref_seq, read_id, _vcf_positions);
  ProcessAlignment(align_ctx, _bam_features);
}

ReadId ComputeBamRegionFeatures::GetReadId(ReadNameToId& read_names,
                                           const std::string& read_name,
                                           ReadId& current_read_id) {
  auto it = read_names.find(read_name);
  if (it != read_names.end()) {
    return it->second;
  }
  auto read_id = current_read_id;
  current_read_id++;
  read_names.try_emplace(read_name, read_id);
  return read_id;
}

}  // namespace xoos::svc
